spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
    locations: classpath:/flyway/db/h2
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
---
spring:
  profiles: local-h2
  flyway:
    locations: classpath:/flyway/db/h2
    enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: local-sql
  flyway:
    locations: classpath:/flyway/db/sql
    enabled: true
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=test
    username: sa
    password: TVMdev2019
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
